### ISSUE TITLE
Please update remove use of "org.gnome.Platform/x86_64/3.34" because it is EOL !!

### ISSUE THREAD

**Issue by Nokia808** [flathub/uk.jnthn.backgammony#1]
Hi. 

1st of all, thank you for bring this nice popular game to FlatHub !

As title saying, this flatpak need update because it is still using "org.gnome.Platform/x86_64/3.34" while it is EOL !!

See the following comments: https://github.com/flathub/flathub/issues/667#issuecomment-764465263 , https://github.com/flathub/flathub/issues/667#issuecomment-764652019

Best regards.

**Comment by jonathanballs** [comment]
Will do! Thank you so much for taking the time to report this.

**Comment by jonathanballs** [comment]
@Nokia808 Could you please link me to a list of the available Gnome runtimes

**Comment by Nokia808** [comment]
@jonathanballs 
Hi dear developer. 
No I do not know ! You should ask the admins of FlatHub - see this page:
https://github.com/https://github.com/orgs/flathub/peopleorgs/flathub/people

You can also use their forum:
https://discourse.flathub.org/

Also, their email is:
admins@flathub.org

I'm just simple desktop user, not a programmer nor a packager .....

Best regards.

**Comment by jonathanballs** [comment]
I see that 3.38 is available - I will update for that this evening.

**Comment by Nokia808** [comment]
@jonathanballs 
Thank you for your hard efforts & work !

**Comment by jonathanballs** [comment]
And thank you for taking the time to report this.
